import SwiftUI

struct DaysTimeSele1Cell: View {
    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Text(StringConstants.kLbl8am)
                .font(FontScheme.kInterSemiBold(size: getRelativeHeight(12.0)))
                .fontWeight(.semibold)
                .foregroundColor(ColorConstants.Gray801)
                .minimumScaleFactor(0.5)
                .multilineTextAlignment(.leading)
                .frame(width: getRelativeWidth(47.0), height: getRelativeHeight(50.0),
                       alignment: .leading)
                .background(ColorConstants.Gray101)
                .padding(.leading, getRelativeWidth(12.0))
            Text(StringConstants.kLbl9am)
                .font(FontScheme.kInterSemiBold(size: getRelativeHeight(12.0)))
                .fontWeight(.semibold)
                .padding(.leading, getRelativeWidth(12.0))
                .padding(.bottom, getRelativeHeight(19.0))
                .padding(.top, getRelativeHeight(18.0))
                .foregroundColor(ColorConstants.Gray801)
                .minimumScaleFactor(0.5)
                .multilineTextAlignment(.leading)
                .frame(width: getRelativeWidth(47.0), height: getRelativeHeight(50.0),
                       alignment: .leading)
                .background(ColorConstants.Gray101)
                .padding(.top, getRelativeHeight(13.0))
            Text(StringConstants.kLbl10am)
                .font(FontScheme.kInterSemiBold(size: getRelativeHeight(12.0)))
                .fontWeight(.semibold)
                .padding(.leading, getRelativeWidth(6.0))
                .padding(.bottom, getRelativeHeight(19.0))
                .padding(.top, getRelativeHeight(18.0))
                .foregroundColor(ColorConstants.Gray801)
                .minimumScaleFactor(0.5)
                .multilineTextAlignment(.leading)
                .frame(width: getRelativeWidth(47.0), height: getRelativeHeight(50.0),
                       alignment: .leading)
                .background(ColorConstants.Lime100)
                .padding(.top, getRelativeHeight(13.0))
            Text(StringConstants.kLbl11am)
                .font(FontScheme.kInterSemiBold(size: getRelativeHeight(12.0)))
                .fontWeight(.semibold)
                .padding(.leading, getRelativeWidth(10.0))
                .padding(.bottom, getRelativeHeight(19.0))
                .padding(.top, getRelativeHeight(18.0))
                .foregroundColor(ColorConstants.Gray801)
                .minimumScaleFactor(0.5)
                .multilineTextAlignment(.leading)
                .frame(width: getRelativeWidth(47.0), height: getRelativeHeight(50.0),
                       alignment: .leading)
                .background(ColorConstants.Lime100)
                .padding(.top, getRelativeHeight(13.0))
            Text(StringConstants.kLbl12pm)
                .font(FontScheme.kInterSemiBold(size: getRelativeHeight(12.0)))
                .fontWeight(.semibold)
                .padding(.leading, getRelativeWidth(6.0))
                .padding(.bottom, getRelativeHeight(18.0))
                .padding(.top, getRelativeHeight(19.0))
                .foregroundColor(ColorConstants.Gray801)
                .minimumScaleFactor(0.5)
                .multilineTextAlignment(.leading)
                .frame(width: getRelativeWidth(47.0), height: getRelativeHeight(50.0),
                       alignment: .leading)
                .background(ColorConstants.Gray101)
                .padding(.top, getRelativeHeight(13.0))
            Text(StringConstants.kLbl1pm)
                .font(FontScheme.kInterSemiBold(size: getRelativeHeight(12.0)))
                .fontWeight(.semibold)
                .padding(.leading, getRelativeWidth(12.0))
                .padding(.bottom, getRelativeHeight(18.0))
                .padding(.top, getRelativeHeight(19.0))
                .foregroundColor(ColorConstants.Gray801)
                .minimumScaleFactor(0.5)
                .multilineTextAlignment(.leading)
                .frame(width: getRelativeWidth(47.0), height: getRelativeHeight(50.0),
                       alignment: .leading)
                .background(ColorConstants.Lime100)
                .padding(.top, getRelativeHeight(13.0))
            Text(StringConstants.kLbl2pm)
                .font(FontScheme.kInterSemiBold(size: getRelativeHeight(12.0)))
                .fontWeight(.semibold)
                .padding(.leading, getRelativeWidth(12.0))
                .padding(.bottom, getRelativeHeight(18.0))
                .padding(.top, getRelativeHeight(19.0))
                .foregroundColor(ColorConstants.Gray801)
                .minimumScaleFactor(0.5)
                .multilineTextAlignment(.leading)
                .frame(width: getRelativeWidth(47.0), height: getRelativeHeight(50.0),
                       alignment: .leading)
                .background(ColorConstants.Gray101)
                .padding(.top, getRelativeHeight(13.0))
            Text(StringConstants.kLbl3pm)
                .font(FontScheme.kInterSemiBold(size: getRelativeHeight(12.0)))
                .fontWeight(.semibold)
                .padding(.leading, getRelativeWidth(11.0))
                .padding(.bottom, getRelativeHeight(18.0))
                .padding(.top, getRelativeHeight(19.0))
                .foregroundColor(ColorConstants.Gray801)
                .minimumScaleFactor(0.5)
                .multilineTextAlignment(.leading)
                .frame(width: getRelativeWidth(47.0), height: getRelativeHeight(50.0),
                       alignment: .leading)
                .background(ColorConstants.Gray101)
                .padding(.top, getRelativeHeight(11.0))
        }
        .frame(width: getRelativeWidth(47.0), alignment: .leading)
        .hideNavigationBar()
    }
}

/* struct DaysTimeSele1Cell_Previews: PreviewProvider {

 static var previews: some View {
 			DaysTimeSele1Cell()
 }
 } */
